language: node_js
node_js: stable
addons:
  ssh_known_hosts: 118.24.152.130
before_install:
- openssl aes-256-cbc -K $encrypted_36f01d5cb599_key -iv $encrypted_36f01d5cb599_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
install:
- cd qblog
- npm install
script:
- hexo clean
- hexo g
- cd ./public
- git init
- git config user.name "antwork"
- git config user.email "antwork@126.com"
- git add .
- git commit -m "Travis CI Auto Builder"
- git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
after_success:
  - ssh root@118.24.152.130 "./pullblog"
branches:
  only:
  - blog-source
env:
  global:
  - GH_REF: github.com/antwork/blog.git
