language: node_js # 设置语言
node_js: stable # 设置相应版本
install:
    - cd qblog
    - npm install # 安装hexo及插件
script:
    - hexo clean # 清除
    - hexo g # 生成
after_script:
    - cd ./public
    - git init
    - git config user.name "antwork" # 修改name
    - git config user.email "antwork@126.com" # 修改email
    - git add .
    - git commit -m "Travis CI Auto Builder"
    - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master # GH_TOKEN是在Travis中配置token的名称
    - ssh root@${CLOUD_IP} -p ${CLOUD_PASS}  # 登录云服务器
    - cd ${CLOUD_PATH} # 打开git文件夹
    - git pull      # 拉取更新

branches:
    only:
        - blog-source #只监测hexo分支，hexo是我的分支的名称，可根据自己情况设置
env:
    global:
        - GH_REF: github.com/antwork/blog.git #设置GH_REF，注意更改yourname